config/routes.rb
Rails.application.routes.draw do
  root "prototypes#index"
  devise_for :users, controllers: {
  registrations: 'users/registrations'
  }
  resources :users, only: :show
  resources :newest, only: :index
  resources :popular, only: :index
  resources :tags, only: [:index, :show]

  resources :prototypes do
    resources :pictures
    resources :comments, only: [:create]
    resources :likes, only: [:create, :destroy]
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :prototype, counter_cache: true
  belongs_to :user
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :prototype, counter_cache: true
  belongs_to :user
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :prototype
  mount_uploader :thumbnail, PicutureUploader
  enum status: %i(main sub)
end

app/models/prototype.rb
class Prototype < ActiveRecord::Base
  belongs_to :user, counter_cache: true
  belongs_to :tag
  has_many :comments
  has_many :pictures, dependent: :destroy
  has_many :likes, dependent: :destroy

  accepts_nested_attributes_for :pictures, reject_if: :reject_pictures

  validates :title, :catchcopy, :concept, presence: true

  acts_as_taggable_on :labels

  paginates_per 5

  def reject_pictures(attributes)
    attributes['thumbnail'].blank?
  end

  def like_user(user)
    likes.find_by(user_id: user.id)
  end

  def sub_img?
    pictures.sub.present?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments
  has_many :prototypes
  has_many :likes
  mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:nickname, :profile, :works, :avatar, :group)
    devise_parameter_sanitizer.for(:account_update).push(:nickname, :profile, :works, :avatar, :group)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @prototype = Prototype.find(comment_params[:prototype_id])
    current_user.comments.create(comment_params)
  end

  private
  def comment_params
    params.require(:comment).permit(:comment).merge(prototype_id: params[:prototype_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    Like.create(user_id: current_user.id, prototype_id: params[:prototype_id])
    @prototype = Prototype.find(params[:prototype_id])
    @likes = @prototype.likes
  end

  def destroy
    Like.find_by(user_id: current_user.id, prototype_id: params[:prototype_id]).destroy
    @prototype = Prototype.find(params[:prototype_id])
    @likes = @prototype.likes
  end

  private
  def id_params
    params.permit(:prototype_id)
  end
end

app/controllers/newest_controller.rb
class NewestController < ApplicationController
  def index
    @prototypes = Prototype.order(id: :desc).includes(:user)
  end
end

app/controllers/popular_controller.rb
class PopularController < ApplicationController
  def index
    @prototypes = Prototype.order(likes_count: :desc).includes(:user)
  end
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  def index
    @prototypes = Prototype.order('rand()').includes(:user).page(params[:page])
  end

  def show
    @prototype = Prototype.find(params[:id])
    @comment = Comment.new
    @comments = @prototype.comments
    @likes = @prototype.likes
  end

  def new
    @prototype = Prototype.new
    @prototype.pictures.build
  end

  def create
    @prototype = current_user.prototypes.create(prototype_params)
    if @prototype.save
      redirect_to action: :index
    else
      render action: :new
    end
  end

  def destroy
    prototype = Prototype.find(params[:id])
    prototype.destroy if prototype.user_id == current_user.id
    redirect_to action: :index
  end

  def edit
    @prototype = Prototype.find(params[:id])
  end

  def update
    prototype = Prototype.find(params[:id])
    prototype.update(prototype_params) if prototype.user_id == current_user.id
    redirect_to action: :index
  end

  private
  def prototype_params
    params.require(:prototype).permit(:title, :catchcopy, :concept, pictures_attributes: [:id, :thumbnail, :status] ).merge(label_list: params[:prototype][:label])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = ActsAsTaggableOn::Tag.all
  end

  def show
    @prototypes = Prototype.tagged_with(params[:id]).page(params[:page])
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  protected
  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @prototypes = @user.prototypes.page(params[:page])
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/comments/_comment.html.haml
.media
  .media-left
    = link_to user_path(comment.user) do
      = image_tag comment.user.avatar, size: "64x64", alt: "64x64", class: 'media-object'
  .media-body
    %h4#top-aligned-media.media-heading 
      = link_to "#{comment.user.nickname}", user_path(comment.user)
      %span.anchorjs-icon
    %p
      = comment.comment

app/views/comments/create.js.erb
$('#comment_area').val('');
$('#comments').html(
  '<%= j(render @prototype.comments) %>'
);
$('span.num').html(
  "<%= j("#{@prototype.comments_count}") %>"
);

app/views/layouts/_footer.html.haml
.container
  %footer
    %p &copy; PROTO SPACE 2015.

app/views/layouts/_header.html.haml
.navbar.navbar-default.navbar-static-top.navbar-fixed-top
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    = link_to image_tag("logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "36px"), '/', class: 'navbar-brand'
    .navbar-collapse.collapse.navbar-responsive-collapse
      - unless user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li
            .btn.btn-primary.navbar-btn
              = link_to "Get Started", new_user_session_path
      - else
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            %a.dropdown-toggle{aria: {expanded: "false"}, data: {toggle: "dropdown"}, href: "#", role:  "button"}
              = current_user.nickname
              %span.caret
            %ul.dropdown-menu{role: "menu"}
              %li
                = link_to "My page", user_path(current_user)
              %li
                = link_to "Profile Edit", edit_user_registration_path(current_user)
              %li
                = link_to "Logout", destroy_user_session_path, method: :delete
          %li
            .btn.btn-primary.navbar-btn
              = link_to "New Proto", new_prototype_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=US-ASCII", http: {equiv: "Content-Type"}}/
    %title Protospace
    = stylesheet_link_tag    'application', media: 'all', data: {turbolinks: {track: "true"}}
    = javascript_include_tag 'application', data: {turbolinks: {track: "true"}}
    = csrf_meta_tags
  %body
    = render "layouts/header"
    = yield
    = render "layouts/footer"

app/views/likes/_like.html.haml
- if user_signed_in?
  - if prototype.like_user(current_user)
    = button_to prototype_like_path(prototype, likes), method: :delete, remote: true, class: "btn btn-default" do
      = image_tag "red_heart.svg"
      Like
      = prototype.likes_count

  - else
    = button_to prototype_likes_path(prototype), method: :create, remote: true, class: "btn btn-default" do
      = image_tag "icon_heart.svg"
      Like
      = prototype.likes_count
- else
  %button.btn.btn-default
    = image_tag "icon_heart.svg"
    Like
    = prototype.likes_count

app/views/likes/create.js.erb
$('#like_button').html(
  '<%= j(render partial: 'likes/like', locals: { prototype: @prototype, likes: @likes }) %>'
);

app/views/likes/destroy.js.erb
$('#like_button').html(
  '<%= j(render partial: 'likes/like', locals: { prototype: @prototype, likes: @likes }) %>'
);

app/views/newest/index.js.erb
$('#proto').html(
  '<%= j( render @prototypes ) %>'
);

app/views/popular/index.js.erb
$('#proto').html(
  '<%= j( render @prototypes ) %>'
);

app/views/prototypes/_comment.html.haml
.media
  .media-left
    %a{ href: "#" }
      %img.media-object
      = image_tag comment.user.avatar, size: "64x64", alt: "64x64"
  .media-body
    %h4#top-aligned-media.media-heading
      = comment.user.nickname
      %a.anchorjs-link{ href: "#top-aligned-media" }
        %span.anchorjs-icon
    = comment.comment

app/views/prototypes/_like.html.haml
- if @prototype.like_user(current_user)
  = button_to prototype_like_path(@prototype, @likes), method: :delete, remote: true, class: "btn btn-default" do
    = image_tag("icon_heart.svg")
    Like
    .num
    = @prototype.likes_count

- else
  = button_to prototype_likes_path(@prototype), method: :create, remote: true, class: "btn btn-default" do
    = image_tag("icon_heart.svg")
    Like
    .num
    = @prototype.likes_count

app/views/prototypes/_nav.html.haml
%ul.nav.nav-pills.col-lg-11
  %li.nav#nav1{role: "presentation"}
    = link_to 'Popular PROTO',popular_index_path, remote: true
  %li.nav#nav2{role: "presentation"}
    = link_to 'Newest PROTO',newest_index_path, remote: true
= button_to 'View Tags', tags_path, method: :get, class: "btn btn-default col-lg-1" 

app/views/prototypes/_prototype.html.haml
.col-sm-4.col-md-3.proto-content
  .thumbnail
    = link_to image_tag(prototype.pictures.main[0].thumbnail), prototype_path(prototype)
    - if user_signed_in? && current_user.id == prototype.user_id
      = link_to 'Delete', prototype_path(prototype), method: :delete
      = link_to 'Edit', edit_prototype_path(prototype), method: :get
    .caption
      %h3
      = prototype.title
      .proto-meta
        .proto-user
          = link_to prototype.user.nickname, user_path(prototype.user)
        .proto-posted
          = prototype.created_at.strftime("%b%d")
      %ul.proto-tag-list.list-inline
      - prototype.labels.each do |label|
        =link_to label.name, tag_path(label.name), class: 'btn btn-default'

app/views/prototypes/comments/_comment.html.haml
.media
  .media-left
    %a{ href: "#" }
      %img.media-object
      = image_tag comment.user.avatar, size: "64x64", alt: "64x64"
  .media-body
    %h4#top-aligned-media.media-heading
      = comment.user.nickname
      %a.anchorjs-link{ href: "#top-aligned-media" }
        %span.anchorjs-icon
    = comment.comment

app/views/prototypes/edit.html.haml
= form_for(@prototype, html: { class: 'container proto-new' }) do |f|
  .col-md-8.col-md-offset-2
    %header.row.user-nav.row
      .col-md-12
        .proto-new-title
          = f.text_field :title, placeholder: "Title"
    .row
      .col-md-12
        .cover-image-upload#upload0
          = f.fields_for :pictures, (@prototype.pictures.main[0]) do |pic|
            = image_tag @prototype.pictures.main[0].thumbnail
            = pic.file_field :thumbnail, class: 'file_zone0'
            = pic.hidden_field :status, value: 'main'

      .col-md-12
      - 3.times do |i|
        %ul.proto-sub-list.list-group
          %li.list-group-item.col-md-4
            .image-upload{id: "upload#{i + 1}"}
              = f.fields_for :pictures, (@prototype.pictures.sub[i]) do |pic|
                = image_tag @prototype.pictures.sub[i].thumbnail if @prototype.sub_img?
                = pic.file_field :thumbnail, class: "file_zone#{i + 1}"
                = pic.hidden_field :status, value: 'sub'

    .row.proto-description
      .col-md-12
        = f.text_field :catchcopy, placeholder: "Catch Copy"
      .col-md-12
        = f.text_area :concept, placeholder: "Concept", cols: "30", rows: "4"
      .col-md-12
        %h4 Tag List
        .row
          .col-md-3
            = text_field_tag "prototype[label][]", "", placeholder: "Web Design"
            = text_field_tag "prototype[label][]", "", placeholder: "UI"
            = text_field_tag "prototype[label][]", "", placeholder: "Application"
    .row.text-center.proto-btn
      = f.submit 'Publish', class: "button btn btn-lg btn-primary btn-block"  

app/views/prototypes/index.html.haml
.jumbotron
  .container.text-center
    = image_tag "header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px"

.filter-nav
  .container
    .row
    = render 'nav'

.container.proto-list
  .row#proto

  = render @prototypes

.text-center
  %ul.pagination
    %li.disabled
      = paginate @prototypes

app/views/prototypes/new.html.haml
= form_for(@prototype, html: { class: 'container proto-new' }) do |f|
  .col-md-8.col-md-offset-2
    %header.row.user-nav.row
      .col-md-12
        .proto-new-title
          = f.text_field :title, placeholder: "Title"
    .row
      .col-md-12
        .cover-image-upload#upload0
          = f.fields_for :pictures do |pic|
            = pic.file_field :thumbnail, class: 'file_zone0'
            = pic.hidden_field :status, value: 'main'

      .col-md-12
      - 3.times do |i|    
        %ul.proto-sub-list.list-group
          %li.list-group-item.col-md-4
            .image-upload{id: "upload#{i + 1}"}
              = f.fields_for :pictures do |pic|
                = pic.file_field :thumbnail, class: "file_zone#{i + 1}"
                = pic.hidden_field :status, value: 'sub'

    .row.proto-description
      .col-md-12
        = f.text_field :catchcopy, placeholder: "Catch Copy"
      .col-md-12
        = f.text_area :concept, placeholder: "Concept", cols: "30", rows: "4"
      .col-md-12
        %h4 Tag List
        .row
          .col-md-3
            = text_field_tag "prototype[label][]", "", placeholder: "Web Design"
            = text_field_tag "prototype[label][]", "", placeholder: "UI"
            = text_field_tag "prototype[label][]", "", placeholder: "Application"
    .row.text-center.proto-btn
      = f.submit 'Publish', class: "button btn btn-lg btn-primary btn-block"  

app/views/prototypes/show.html.haml
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          %img.media-object
            = image_tag @prototype.user.avatar, size: "64x64", alt: "64x64"
        .media-body
          %h4#top-aligned-media.media-heading
            = @prototype.title
          .proto-user
            = link_to "by #{@prototype.user.nickname}", user_path(@prototype.user)
            %span.degree
            = @prototype.user.group

    .col-md-6.text-right#like_button
      = render partial: 'likes/like', locals: { prototype: @prototype, likes: @likes }

  .row
    .col-md-9
      = image_tag @prototype.pictures.main[0].thumbnail, class: 'img-responsive'
    - if @prototype.pictures.sub.present?
      .col-md-3
        %ul.proto-sub-list.list-group
          %li.list-group-item
          - @prototype.pictures.sub.each do |sub|
            = image_tag sub.thumbnail, class: 'img-responsive'
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p
      = @prototype.catchcopy
    .col-md-6
      %h4 Concept
      %p
      = @prototype.concept
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inlines
      - @prototype.labels.each do |label|
        =link_to label.name, tag_path(label.name), class: 'btn btn-default'

  .row.proto-comments
    %h4.col-md-12
      Comments
      %span.num
      = @prototype.comments_count
    #comments.col-md-8
      = render @comments

    - if user_signed_in?
      = form_for [@prototype, @comment], remote: true do |f|
        %h4 Write a comment
        .row
          .form-group.col-md-10
            = f.text_area :comment, placeholder: "Your comments", rows: "3", class: "textarea form-control", id: "comment_area"
          .form-group.col-md-2
            = f.submit 'Comment', class: "button btn btn-primary"

app/views/tags/index.html.haml
.container
  .row
    .tags-list
      %ul
        %h2 Tags List
        - @tags.each do |label|
          .col-md-4
            = link_to label.name, tag_path(label.name), class: 'btn btn-default', id: 'tag_btn_nav'

app/views/tags/show.html.haml
.jumbotron
  .container.text-center
    = image_tag "header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px"

.filter-nav
  .container
    .row
    = render 'prototypes/nav'

.container.proto-list
  .row#proto

  = render @prototypes

.text-center
  %ul.pagination
    %li.disabled
      = paginate @prototypes

app/views/top/_index.html.haml
.col-sm-4.col-md-3.proto-content
  .thumbnail
    %a{:href => ""}
      = image_tag("sample.png")
      .caption
        %h3 Salvation Army on iPad App Wireframe
        .proto-meta
          .proto-user
            %a{:href => "#"} by user
          .proto-posted
            Apr 26
        %ul.proto-tag-list.list-inline
          %li 
            %a{:href => "#", :class => "btn btn-default"} iPad
          %li 
            %a{:href => "#", :class => "btn btn-default"} wireframe

app/views/users/index.html.haml
.container.user-page
  %header.user-nav
    .media
      .media-left
        %a{href: "#"}
          %img.media-object{alt: "64x64", data: {holder: {rendered: "true"}, data: {src: "holder.js/64x64"}, src: "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+PGRlZnMvPjxyZWN0IHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjEzLjQ2MDkzNzUiIHk9IjMyIiBzdHlsZT0iZmlsbDojQUFBQUFBO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1mYW1pbHk6QXJpYWwsIEhlbHZldGljYSwgT3BlbiBTYW5zLCBzYW5zLXNlcmlmLCBtb25vc3BhY2U7Zm9udC1zaXplOjEwcHQ7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+NjR4NjQ8L3RleHQ+PC9nPjwvc3ZnPg==", style: "width: 64px; height: 64px;"}/
      .media-body
        %h4#top-aligned-media.media-heading
          Top aligned media
          %span.label.label-default.project-number
            29
            %i Projects
        .proto-user
          %span.degree we-b inc. Designer
        .row
          .col-md-6
            %h4 Profile
            %p Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
          .col-md-6
            %h4 Works
            %p Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
.container.proto-list
  .row
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{href: ""}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                %a{href: "#", class: "btn btn-default"} iPad
              %li 
                %a{href: "#", class: "btn btn-default"} wireframe
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{href: ""}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                %a{href: "#", class: "btn btn-default"} iPad
              %li 
                %a{href: "#", class: "btn btn-default"} wireframe
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{href: ""}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                %a{href: "#", class: "btn btn-default"} iPad
              %li 
                %a{href: "#", class: "btn btn-default"} wireframe
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{href: ""}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                %a{href: "#", class: "btn btn-default"} iPad
              %li 
                %a{href: "#", class: "btn btn-default"} wireframe
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{href: ""}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                %a{href: "#", class: "btn btn-default"} iPad
              %li 
                %a{href: "#", class: "btn btn-default"} wireframe

.text-center
  %ul.pagination
    %li.disabled
      %a{aria: {label: "Previous"}, href: "#"}
        %span aria: {hidden: "true"} «
    %li.active
      %a{href: "#"}
        1
        %span.sr-only (current)
    %li
      %a{href: "#"} 2
    %li
      %a{href: "#"} 3
    %li
      %a{href: "#"} 4
    %li
      %a{href: "#"} 5
    %li
      %a{aria: {label: "Next"}, href: "#"}
        %span{aria: {hidden: "true"} »

app/views/users/new.html.haml
%form.container.user-new{action: ""}
  .col-md-8.col-md-offset-2
    %header.row.user-nav.row
      .col-md-12
        %h2 Register
        .user-name_image.row
          .user-name.col-md-10
            %input{type: "text", placeholder: "Username"}/
          .user-image.col-md-2
            %button.btn.btn-primary Add image
            %input{type: "file"}/
        %input.user-email{type: "email", placeholder: "E-Mail"}/
        %input.user-password{type: "password", placeholder: "Password"}/
      .col-md-12
        %h4 Member of
        .user-user-member.row
          .user-name.col-md-12
            %input{type: "text", placeholder: "Member"}/
        %h4 Profile
        .user-user-profile.row
          .user-name.col-md-12
            %textarea{name: "textarea", cols: "30", rows: "4", placeholder: "Profile"}
        %h4 Works 
        .user-name_image.row
          .user-name.col-md-12
            %textarea{name: "textarea", cols: "30", rows: "4", placeholder: "Works"}
    .row.text-center.user-btn
      %button.btn.btn-lg.btn-primary.btn-block{type: "submit"} Save

app/views/users/show.html.haml
.container.user-page
  %header.user-nav
    .media
      .media-left
        %img.media-object
        = image_tag @user.avatar, size: "64x64", alt: "64x64"
      .media-body
        %h4#top-aligned-media.media-heading
          Top aligned media
          %span.label.label-default.project-number
            = @user.prototypes_count
            %i Projects
        .proto-user
          %span.degree
          = @user.group
        .row
          .col-md-6
            %h4 Profile
            %p
            = @user.profile
          .col-md-6
            %h4 Works
            %p
            = @user.works
.container.proto-list
  .row
  - @user.prototypes.each do |prototype|
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        = link_to prototype_path(prototype) do
          = image_tag(prototype.pictures.main[0].thumbnail)
          .caption
            %h3
            = prototype.title
            .proto-meta
              .proto-user
                %a
                = link_to prototype.user.nickname, user_path(prototype.user)
              .proto-posted
                = prototype.created_at.strftime("%b%d")
            %ul.proto-tag-list.list-inline
              %li 
                %a{href: "#", class: "btn btn-default"}   iPad
              %li 
                %a{href: "#", class: "btn btn-default"}   wireframe

.text-center
  %ul.pagination
    %li.disabled
      = paginate @prototypes